### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: 'void android.widget.LinearLayout.setVisibility(int)' on a null object reference

### ISSUE THREAD

**Issue by juarezfranco** [Wootric/WootricSDK-flutter#8]
Some users are get this:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setVisibility(int)' on a null object reference
       at com.wootric.androidsdk.views.SurveyFragment.onCreateView(SurveyFragment.java:78)
       at android.app.Fragment.performCreateView(Fragment.java:2505)
       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1303)
       at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
       at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
       at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
       at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
       at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by juarezfranco** [comment]
It's happens only on tablet

**Comment by diegoserranoa** [comment]
Hi @juarezfranco thanks for reporting this and sorry for the late response.

I'm working on the fix and will let you know once the patch has been rolled out.
